import smtplib
import base64
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email.mime.image import MIMEImage
from email import encoders
from pathlib import Path
from datetime import datetime
from typing import Optional

# SMTP configuration
SMTP_HOST = "192.168.1.100"
SMTP_PORT = 25
FROM_ADDR = "ab@lasertechno.ru"
TO_ADDR = "shtamp_error@lasertechno.ru"


def _build_html_body(filename: str, problems: list, total_segments: int, tolerance: float, svg_content: str) -> str:
    rows = ""
    for p in problems:
        loc = p.get("location", (0, 0))
        dist = p.get("distance", 0)
        l1 = p.get("segment1", {})
        l2 = p.get("segment2", {})
        layer1 = getattr(l1, "layer", "?")
        layer2 = getattr(l2, "layer", "?")
        type1 = getattr(l1, "entity_type", "?")
        type2 = getattr(l2, "entity_type", "?")
        rows += f"""<tr>
          <td style="padding:8px 12px;border-bottom:1px solid #333;text-align:center">#{p.get("id", "?")}</td>
          <td style="padding:8px 12px;border-bottom:1px solid #333;color:#fbbf24">{dist:.4f} mm</td>
          <td style="padding:8px 12px;border-bottom:1px solid #333">{layer1} / {layer2}</td>
          <td style="padding:8px 12px;border-bottom:1px solid #333">{type1} / {type2}</td>
          <td style="padding:8px 12px;border-bottom:1px solid #333;color:#888">{loc[0]:.2f}, {loc[1]:.2f}</td>
        </tr>"""

    return f"""<html><body style="font-family:'Segoe UI',sans-serif;background:#0f0f1a;color:#e0e0e0;padding:30px">
<div style="max-width:700px;margin:0 auto;background:#16162a;border:1px solid #2a2a4a;border-radius:12px;overflow:hidden">
<div style="background:#1a1a35;padding:24px;border-bottom:1px solid #2a2a4a">
<h1 style="margin:0;font-size:18px;color:#b0b0d0">DXF Double Line Checker Report</h1>
<p style="margin:6px 0 0;font-size:14px;color:#e0e0ff">{filename}</p>
<p style="margin:4px 0 0;font-size:12px;color:#888">{datetime.now().strftime("%d.%m.%Y %H:%M")} | Segments: {total_segments} | Tolerance: {tolerance} mm</p>
</div>
<div style="padding:24px">
<div style="background:#3a1a1a;border:1px solid #5a2a2a;border-radius:8px;padding:12px 16px;margin-bottom:20px">
<p style="margin:0;color:#f87171;font-size:15px;font-weight:600">Found {len(problems)} problem(s)</p>
</div>
<table style="width:100%;border-collapse:collapse;font-size:13px">
<thead><tr style="background:#1a1a35">
<th style="padding:8px 12px;text-align:center;border-bottom:2px solid #2a2a4a;color:#888">#</th>
<th style="padding:8px 12px;text-align:left;border-bottom:2px solid #2a2a4a;color:#888">Distance</th>
<th style="padding:8px 12px;text-align:left;border-bottom:2px solid #2a2a4a;color:#888">Layer</th>
<th style="padding:8px 12px;text-align:left;border-bottom:2px solid #2a2a4a;color:#888">Type</th>
<th style="padding:8px 12px;text-align:left;border-bottom:2px solid #2a2a4a;color:#888">Location</th>
</tr></thead>
<tbody>{rows}</tbody></table>
</div>
<div style="padding:0 24px 24px">
<p style="font-size:11px;color:#555">Generated by DXF Double Line Checker</p>
</div>
</div></body></html>"""


def send_report_email(
    filename: str,
    report_path: Optional[str],
    problems: list,
    total_segments: int,
    tolerance: float,
    svg_base: str = "",
    svg_problems: str = "",
) -> dict:
    try:
        msg = MIMEMultipart("mixed")
        msg["From"] = FROM_ADDR
        msg["To"] = TO_ADDR
        msg["Subject"] = f"DXF Checker Report — {filename} ({len(problems)} problems)"

        # HTML body
        html_body = _build_html_body(filename, problems, total_segments, tolerance, svg_base)
        msg_alt = MIMEMultipart("alternative")
        msg_alt.attach(MIMEText(html_body, "html", "utf-8"))
        msg.attach(msg_alt)

        # Attach HTML report file if exists
        if report_path and Path(report_path).exists():
            with open(report_path, "rb") as f:
                part = MIMEBase("application", "octet-stream")
                part.set_payload(f.read())
                encoders.encode_base64(part)
                part.add_header("Content-Disposition", f'attachment; filename="{Path(report_path).name}"')
                msg.attach(part)

        with smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=10) as server:
            server.send_message(msg)

        return {"ok": True, "message": "Email sent"}
    except Exception as e:
        return {"ok": False, "message": str(e)}
